name: Terraform Deployment S3

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.4 # Outdated but it is my current version on desktop
        with:
          terraform_version: 1.3.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-deployment

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform-deployment

      - name: Terraform Output
        run: terraform output
        working-directory: terraform-deployment